TEXTS = {
    "uz": {
        "welcome": "👋 <b>Xush kelibsiz!</b>\nSiz ariza topshirish jarayonini boshlayapsiz.\n\n⏳ Bu jarayon 2-3 daqiqa vaqt oladi.",
        "ask_first_name": "👉 <b>Ismingizni kiriting</b> <i>(Masalan: Ali)</i>:",
        "ask_last_name": "👉 <b>Familiyangizni kiriting</b> <i>(Masalan: Valiyev)</i>:",
        "ask_father_name": "👉 <b>Otasining ismini kiriting</b> <i>(Masalan: G'ani o'g'li)</i>:",
        "ask_phone": "👉 <b>Telefon raqamingizni yuboring:</b>",
        "ask_email": "👉 <b>Email manzilingizni kiriting:</b>",
        "invalid_email": "❌ Noto'g'ri email formati. Qaytadan kiriting:",
        "ask_region": "👉 <b>Viloyatingizni tanlang:</b>",
        "ask_district": "👉 <b>Tumaningizni tanlang:</b>",
        "ask_passport": "👉 <b>Pasport raqamini kiriting (Format: AD1234567):</b>",
        "invalid_passport": "❌ Noto'g'ri pasport formati. Format AD1234567 kabi bo'lishi kerak. Qaytadan kiriting:",
        "file_too_large": "❌ Fayl hajmi 20MB dan oshmasligi kerak!",
        "ask_passport_file": "📎 <b>Pasport rasmini yoki PDF faylini yuklang:</b>",
        "ask_birth_date": "👉 <b>Tug'ilgan sanangizni kiriting (KK.OO.YYYY, masalan: 01.12.2000):</b>",
        "ask_diplom_file": "🎓 <b>Diplom yoki Atestat rasmini yoxud PDF faylini yuklang:</b>",
        "ask_direction": "🎓 <b>Yo'nalishni tanlang:</b>",
        "ask_msc_type": "🎓 <b>O'quv shaklini tanlang:</b>",
        "full_time": "1 yillik ta'lim (Full time)",
        "part_time": "2 yillik ta'lim (Part time)",
        "ask_certificate": "📜 <b>Sertifikat yuklang (IELTS / CEFR / DUOLINGO):</b>",
        "confirmation": "📋 <b>Ushbu ma'lumotlar to'g'riligini tasdiqlaysizmi?</b>\n\n<b>Ism:</b> {ism}\n<b>Familiya:</b> {familiya}\n<b>Ota ism:</b> {otasining_ismi}\n<b>Tel:</b> {telefon}\n<b>Yonalish:</b> {yonalish}\n\n📌 <i>Ma’lumotlaringizni qayta ishlash va 3-shaxsga yuborishga rozimisiz?</i>",
        "success": "✅ <b>Arizangiz muvaffaqiyatli qabul qilindi!</b>\n\nOperatorlarimiz tez orada siz bilan bog'lanishadi.",
        "cancelled": "❌ <b>Bekor qilindi va ma'lumotlar o'chirildi.</b>\n\n🔄 Qaytadan kiritasizmi? /start ni bosing.",
        "phone_keyboard_text": "📱 Telefon raqamni yuborish",
        "confirm_yes": "✅ Roziman",
        "confirm_no": "❌ Yo‘q",
    },
    "ru": {
        "welcome": "👋 <b>Добро пожаловать!</b>\nВы начинаете процесс подачи заявления.\n\n⏳ Этот процесс займет 2-3 минуты.",
        "ask_first_name": "👉 <b>Введите ваше имя</b> <i>(Например: Али)</i>:",
        "ask_last_name": "👉 <b>Введите вашу фамилию</b> <i>(Например: Валиев)</i>:",
        "ask_father_name": "👉 <b>Введите ваше отчество</b> <i>(Например: Ганиевич)</i>:",
        "ask_phone": "👉 <b>Отправьте ваш номер телефона:</b>",
        "ask_email": "👉 <b>Введите ваш адрес электронной почты:</b>",
        "invalid_email": "❌ Неверный формат электронной почты. Введите еще раз:",
        "ask_region": "👉 <b>Выберите ваш регион:</b>",
        "ask_district": "👉 <b>Выберите ваш район:</b>",
        "ask_passport": "👉 <b>Введите номер паспорта (Формат: AD1234567):</b>",
        "invalid_passport": "❌ Неверный формат паспорта. Формат должен быть как AD1234567. Введите еще раз:",
        "file_too_large": "❌ Размер файла не должен превышать 20 МБ!",
        "ask_passport_file": "📎 <b>Загрузите фото паспорта или PDF-файл:</b>",
        "ask_birth_date": "👉 <b>Введите дату вашего рождения (ДД.ММ.ГГГГ, например: 01.12.2000):</b>",
        "ask_diplom_file": "🎓 <b>Загрузите фото диплома или аттестата либо PDF-файл:</b>",
        "ask_direction": "🎓 <b>Выберите направление:</b>",
        "ask_msc_type": "🎓 <b>Выберите форму обучения:</b>",
        "full_time": "Очная (Full time)",
        "part_time": "Заочная (Part time)",
        "ask_certificate": "📜 <b>Загрузите сертификат (IELTS / CEFR / DUOLINGO):</b>",
        "confirmation": "📋 <b>Подтверждаете ли вы правильность этих данных?</b>\n\n<b>Имя:</b> {ism}\n<b>Фамилия:</b> {familiya}\n<b>Отчество:</b> {otasining_ismi}\n<b>Тел:</b> {telefon}\n<b>Направление:</b> {yonalish}\n\n📌 <i>Согласны ли вы на обработку ваших данных и их передачу третьим лицам?</i>",
        "success": "✅ <b>Ваше заявление успешно принято!</b>\n\nАдминистраторы свяжутся с вами в ближайшее время.",
        "cancelled": "❌ <b>Отменено и данные удалены.</b>\n\n🔄 Ввести заново? Нажмите /start.",
        "phone_keyboard_text": "📱 Отправить номер телефона",
        "confirm_yes": "✅ Согласен",
        "confirm_no": "❌ Нет",
    },
    "en": {
        "welcome": "👋 <b>Welcome!</b>\nYou are starting the application process.\n\n⏳ This process will take 2-3 minutes.",
        "ask_first_name": "👉 <b>Enter your first name</b> <i>(e.g., Ali)</i>:",
        "ask_last_name": "👉 <b>Enter your last name</b> <i>(e.g., Valiyev)</i>:",
        "ask_father_name": "👉 <b>Enter your father's name</b> <i>(e.g., Gani)</i>:",
        "ask_phone": "👉 <b>Send your phone number:</b>",
        "ask_email": "👉 <b>Enter your email address:</b>",
        "invalid_email": "❌ Invalid email format. Please re-enter:",
        "ask_region": "👉 <b>Select your region:</b>",
        "ask_district": "👉 <b>Select your district:</b>",
        "ask_passport": "👉 <b>Enter passport number (Format: AD1234567):</b>",
        "invalid_passport": "❌ Invalid passport format. It should be like AD1234567. Please re-enter:",
        "file_too_large": "❌ File size may not exceed 20MB!",
        "ask_passport_file": "📎 <b>Upload a photo of your passport or a PDF file:</b>",
        "ask_birth_date": "👉 <b>Enter your date of birth (DD.MM.YYYY, e.g.: 01.12.2000):</b>",
        "ask_diplom_file": "🎓 <b>Upload a photo of your diploma or certificate or a PDF file:</b>",
        "ask_direction": "🎓 <b>Choose a direction:</b>",
        "ask_msc_type": "🎓 <b>Choose study type:</b>",
        "full_time": "Full time",
        "part_time": "Part time",
        "ask_certificate": "📜 <b>Upload certificate (IELTS / CEFR / DUOLINGO):</b>",
        "confirmation": "📋 <b>Do you confirm the accuracy of this data?</b>\n\n<b>First Name:</b> {ism}\n<b>Last Name:</b> {familiya}\n<b>Father's Name:</b> {otasining_ismi}\n<b>Tel:</b> {telefon}\n<b>Direction:</b> {yonalish}\n\n📌 <i>Do you agree to the processing of your data and its transfer to a third party?</i>",
        "success": "✅ <b>Your application has been successfully accepted!</b>\n\nAdministrators will contact you shortly.",
        "cancelled": "❌ <b>Cancelled and data deleted.</b>\n\n🔄 Do you want to re-enter? Press /start.",
        "phone_keyboard_text": "📱 Send phone number",
        "confirm_yes": "✅ I agree",
        "confirm_no": "❌ No",
    }
}
